# Generated by Django 3.0.2 on 2020-06-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0002_auto_20200616_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subskribe_id', models.IntegerField(null=True)),
                ('subskribe', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subskriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subskriber_id', models.IntegerField(null=True)),
                ('subskriber', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subskribe',
            field=models.ManyToManyField(to='my_vk.Subscribe'),
        ),
        migrations.AddField(
            model_name='user',
            name='subskriber',
            field=models.ManyToManyField(to='my_vk.Subskriber'),
        ),
    ]
