# Generated by Django 3.0.2 on 2020-06-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0003_auto_20200618_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subskribe',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subskriber',
            name='subskriber',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
