# Generated by Django 3.0.2 on 2020-06-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0004_auto_20200618_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follofing',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_follofing_+', to='my_vk.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='follovers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_follovers_+', to='my_vk.User'),
        ),
    ]
