# Generated by Django 3.0.2 on 2020-06-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0005_auto_20200619_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subskribe',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subskriber',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
        migrations.DeleteModel(
            name='Subskriber',
        ),
    ]
