# Generated by Django 3.0.2 on 2020-06-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0010_remove_user_follovers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follovers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_follovers_+', to='my_vk.User'),
        ),
    ]
