# Generated by Django 3.0.2 on 2020-06-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0011_user_follovers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follofing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follovers',
        ),
    ]
