# Generated by Django 3.0.2 on 2020-06-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0014_auto_20200620_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follofing',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_vk.User')),
            ],
        ),
        migrations.CreateModel(
            name='Follof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follof', models.ManyToManyField(to='my_vk.User')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_vk.UserProfile')),
            ],
        ),
    ]
