# Generated by Django 3.0.2 on 2020-06-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0015_auto_20200620_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
