# Generated by Django 3.0.2 on 2020-06-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0017_auto_20200620_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follof',
            name='user',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_vk.User')),
            ],
        ),
        migrations.AddField(
            model_name='follof',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_vk.UserProfile'),
        ),
    ]
