# Generated by Django 3.0.2 on 2020-06-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0018_auto_20200620_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follof',
            name='profil',
        ),
        migrations.AddField(
            model_name='follof',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_user', to='my_vk.User'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
