# Generated by Django 3.0.2 on 2020-06-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0019_auto_20200620_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follof',
            name='follof',
            field=models.ManyToManyField(null=True, to='my_vk.User'),
        ),
    ]
