# Generated by Django 3.0.2 on 2020-06-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0022_auto_20200620_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follof',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_user', to='my_vk.User', unique=True),
        ),
    ]
