# Generated by Django 3.0.2 on 2020-06-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0023_auto_20200620_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follof',
            name='follof',
            field=models.ManyToManyField(to='my_vk.User'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(upload_to='posts/', verbose_name='добавьте пост')),
                ('like', models.ManyToManyField(to='my_vk.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='my_vk.User')),
            ],
        ),
    ]
