# Generated by Django 3.0.2 on 2020-06-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0024_auto_20200624_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
