# Generated by Django 3.0.2 on 2020-06-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0025_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.ImageField(upload_to='posts/', verbose_name='добавьте пост')),
                ('like', models.ManyToManyField(blank=True, to='my_vk.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='my_vk.User')),
            ],
        ),
    ]
