# Generated by Django 3.0.2 on 2020-06-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0027_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
