# Generated by Django 3.0.2 on 2020-06-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0029_auto_20200624_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ImageField(blank=True, upload_to='posts/', verbose_name='добавьте пост'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
