# Generated by Django 3.0.2 on 2020-06-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0030_auto_20200624_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(blank=True, upload_to='posts/', verbose_name='добавьте пост')),
                ('comment', models.TextField(blank=True)),
                ('like', models.ManyToManyField(to='my_vk.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='my_vk.User')),
            ],
        ),
        migrations.AlterField(
            model_name='follof',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_user', to='my_vk.User'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
