# Generated by Django 3.0.2 on 2020-06-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0031_auto_20200624_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Comment',
        ),
    ]
