# Generated by Django 3.0.2 on 2020-06-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0033_auto_20200627_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('comment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='my_vk.Post')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_vk.User')),
            ],
        ),
    ]
