# Generated by Django 3.0.2 on 2020-06-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0034_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follofing',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_follofing_+', to='my_vk.User'),
        ),
        migrations.DeleteModel(
            name='Follof',
        ),
    ]
