# Generated by Django 3.0.2 on 2020-06-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0036_auto_20200629_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follofing',
            field=models.ManyToManyField(blank=True, to='my_vk.User'),
        ),
    ]
