# Generated by Django 3.0.2 on 2020-06-29 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0037_auto_20200629_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 20, 29, 51, 300226)),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 20, 29, 51, 299226)),
        ),
    ]
