# Generated by Django 3.0.2 on 2020-08-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0046_auto_20200731_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to='my_vk.User'),
        ),
    ]
