# Generated by Django 3.0.2 on 2020-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vk', '0047_auto_20200804_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/avatar/anonim-avatar.jpg', upload_to='avatar/', verbose_name='фото профиля'),
        ),
    ]
